apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: autopirate
  creationTimestamp: null
  labels:
    io.kompose.service: downloads
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ceph-filesystem
status: {}
