apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: autopirate
  creationTimestamp: null
  labels:
    io.kompose.service: downloads
  name: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: openebs-hostpath
status: {}
