apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: autopirate
  creationTimestamp: null
  labels:
    io.kompose.service: downloads
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
status: {}
