apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sonarr-helm-chart-value-overrides
  namespace: sonarr
data:
  values.yaml: |-
    image:
      repository: tccr.io/truecharts/sonarr
      pullPolicy: IfNotPresent
      tag: 3.0.9.1549@sha256:294b6288d91346f6e65f8cb344b42d17c97b3ee7ada501d77307088f79a8dc15

    service:
      main:
        type: LoadBalancer
        ports:
          main:
            port: 8989
            targetPort: 8989

    probes:
      liveness:
        enabled: true
        ## Set this to true if you wish to specify your own livenessProbe
        custom: true
        ## The spec field contains the values for the default livenessProbe.
        ## If you selected custom: true, this field holds the definition of the livenessProbe.
        spec:
          exec:
            command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
                read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10

    persistence:
      config:
        enabled: true
        mountPath: "/config"

    portal:
      enabled: true