apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: autopirate
  creationTimestamp: null
  labels:
    io.kompose.service: tv
  name: tv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: openebs-hostpath
status: {}
