version: "2.1"
services:
  sonarr:
    labels:
      kompose.service.type: loadbalancer
      kompose.volume.storage-class-name: longhorn
      kompose.service.expose: "sonarr.epricesx.duckdns.org"
      kompose.service.expose.ingress-class-name: "nginx"
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr:/config
      - tv:/tv #optional
      - downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: always
volumes:
  sonarr:
  tv:
  downloads: