version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr:/config
      - tv:/tv #optional
      - downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: always
volumes:
  sonarr:
  tv:
  downloads: