apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: autopirate
  creationTimestamp: null
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
status: {}
