apiVersion: v1
kind: Service
metadata:
  namespace: adguard-home
  name: adguard-home
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.200
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adguard-home
  externalTrafficPolicy: Local
  ports:
  - name: adguard-home
    port: 10232
    targetPort: 10232
    protocol: TCP
  - name: adguard-home
    port: 10232
    targetPort: 10232
    protocol: TCP
  - name: adguard-home-dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: adguard-home-dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - name: adguard-home-dhcp-udp-2
    port: 68
    targetPort: 68
    protocol: UDP
  - name: adguard-home-dhcp-tcp
    port: 68
    targetPort: 68
    protocol: TCP