apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: adguard-home-helm-chart-value-overrides
  namespace: adguard-home
data:
  values.yaml: |-
    image:
      repository: tccr.io/truecharts/adguard-home
      tag: 0.107.25@sha256:90e78953b5e15126b151ac655e37ad161bf5a6f10e2cdbb50da7f68166f57719
      pullPolicy: IfNotPresent

    # Those args are copied from the upstream Dockerfile.
    # Only port was added. So Adguard won't change port after initial setup
    args:
      - --no-check-update
      - --host
      - "0.0.0.0"
      - --config
      - /opt/adguardhome/conf/AdGuardHome.yaml
      - --work-dir
      - /opt/adguardhome/work
      - --port
      - "{{ .Values.service.main.ports.main.port }}"

    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0

    probes:
      liveness:
        type: HTTP
        path: /
      readiness:
        type: HTTP
        path: /
      startup:
        type: HTTP
        path: /

    persistence:
      config:
        enabled: true
        mountPath: "/opt/adguardhome/conf"
      data:
        enabled: true
        mountPath: "/opt/adguardhome/work"

    portal:
      enabled: true
