apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  chart:
    spec:
      chart: adguard-home
      version: 13.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: adguard-home
  valuesFrom:
  - kind: ConfigMap
    name: adguard-home-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity