apiVersion: v1
kind: Service
metadata:
  namespace: adguard-home
  name: adguard-home-dhcp
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.200
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - protocol: UDP
      port: 67
      targetPort: 67