apiVersion: v1
kind: Service
metadata:
  namespace: adguard-home
  name: adguard-home-dhcp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - protocol: UDP
      port: 67
      targetPort: 67