---
version: "2.1"
services:
  jellyfin:
    labels:
      kompose.service.type: loadbalancer
      kompose.volume.storage-class-name: longhorn
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - jellyfin:/config
      - tv:/data/tvshows
      - movie:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: always
volumes:
  jellyfin:
  tv:
  movie: