version: "2.1"
services:
  transmission:
    labels:
      kompose.service.type: loadbalancer
      kompose.volume.storage-class-name: longhorn
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - transmission:/config
      - downloads:/downloads 
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
volumes:
  transmission:
  downloads: